/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.ItemEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTable;
import javax.swing.SpinnerDateModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author fservin
 */
public class Formato6 extends javax.swing.JFrame {
    
    private DefaultTableModel tabla,tabla2;
    private float largo;
    private int fila, D1, D2, cont;
    private double volTotal2, volTotal;
    private double Vol  = 1;
    private double dAncho , dLargo , dEspesor ;
    private double dDiametro1, dDiametro2,dMILargo;
    private String Clasificacion;
    
    private double d1 = 0,d2 = 0,uno = 0;
    private BigDecimal a = null,b;
    DecimalFormat decimales = new DecimalFormat("0.00");
    private double  largos,Voltroza;
    private String [] Largos =  {"1.25","2.62","Especiales"};
    private String [] Clas = {"Primario","Secundario","Tercera","Celulosicos","Medidas Especiales","Puntales","Morillos"};
    private String [] desc = {"Tabla","Tableta","Tablon","Vigas","Viguetas","Madera Dimensionada","Polines","Medidas Especiales"};
    private String [] calidad ={"Primario","Secundario","Tercera","Cuarta","Quinta"};
    private JComboBox jcbClas;
    private JComboBox jcbLargos;
    private JComboBox jcbDescripcion2;
    private JComboBox jcbCalidad2;
    
    public int piezas;
    public double diame1,diame2;
    
    private void anadeListenerAlModelo(JTable tabla) {
        tabla.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent evento) {
                actualizaTabla(evento);
            }  
        });
    }
    
    private void anadeListenerAlModelo2(JTable tabla) {
        tabla.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent evento) {
                actualizaTabla2(evento);
            }  
        });
    }
    /**
     * Creates new form Formato6
     */
    public Formato6() {
        
        initComponents();
        
        tabla = (DefaultTableModel) jtRMR.getModel();
        tabla2 = (DefaultTableModel) jtProductosAserrados.getModel();
        
        anadeListenerAlModelo(jtRMR);
        anadeListenerAlModelo2(jtProductosAserrados);
        
        jsHoraEntrada = new JSpinner( new SpinnerDateModel() );
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jsHoraEntrada, "HH:mm:ss");
        jsHoraEntrada.setEditor(timeEditor);
        jsHoraEntrada.setValue( new Date() );
      
        jcbClas = new JComboBox(Clas);
        TableColumn columnaC = jtRMR.getColumnModel().getColumn(1);
        TableCellEditor tceC = new DefaultCellEditor(jcbClas);
        columnaC.setCellEditor(tceC);
        
        jcbLargos = new JComboBox(Largos);
        TableColumn  columnaL = jtRMR.getColumnModel().getColumn(2);
        TableCellEditor tceL = new DefaultCellEditor(jcbLargos);
        columnaL.setCellEditor(tceL);       
        
        //**********************************************************************
        
        jcbDescripcion2 = new JComboBox(desc);
        TableColumn colDes = jtProductosAserrados.getColumnModel().getColumn(0);
        TableCellEditor tceDes = new DefaultCellEditor(jcbDescripcion2);
        colDes.setCellEditor(tceDes);
        
        jcbCalidad2 = new JComboBox(calidad);
        TableColumn colCali = jtProductosAserrados.getColumnModel().getColumn(1);
        TableCellEditor tceCali = new DefaultCellEditor(jcbCalidad2);
        colCali.setCellEditor(tceCali);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dcFechaIngreso = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        txfComunidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtRMR = new javax.swing.JTable();
        lbVolTotal = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txfResponsable = new javax.swing.JTextField();
        jcbProcedencia = new javax.swing.JComboBox();
        jcbGenero = new javax.swing.JComboBox();
        btnEliminarFilaMI = new javax.swing.JButton();
        btnAgregarFilaMI = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel( date, null, null, Calendar.HOUR_OF_DAY );
        jsHoraEntrada = new javax.swing.JSpinner(sm);
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductosAserrados = new javax.swing.JTable();
        btnAgregaFilaPA = new javax.swing.JButton();
        btnEliminaFilaPA = new javax.swing.JButton();
        btnGuardarF6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblPAVolTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Fecha de Ingreso");

        jLabel5.setText("Comunidad");

        txfComunidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfComunidadKeyTyped(evt);
            }
        });

        jLabel6.setText("Procedencia");

        jLabel8.setText("Genero");

        jtRMR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza", "Clasificacion", "Largo", "D1", "D2", "DM", "M3R"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRMR.setColumnSelectionAllowed(true);
        jtRMR.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtRMR);
        jtRMR.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel23.setText("Responsable : ");

        txfResponsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfResponsableKeyTyped(evt);
            }
        });

        jcbProcedencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Propia", "Maquila" }));

        jcbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pino", "Encino", "Latifoliadas" }));

        btnEliminarFilaMI.setText("Eliminar Fila");
        btnEliminarFilaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaMIActionPerformed(evt);
            }
        });

        btnAgregarFilaMI.setText("Agregar Fila");
        btnAgregarFilaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaMIActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel15.setText("Volumen Total: ");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jsHoraEntrada, "HH:mm:ss");
        jsHoraEntrada.setEditor(de);

        jLabel7.setText("Hora de Entrada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarFilaMI)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarFilaMI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(49, 49, 49)
                                .addComponent(txfComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(lbVolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jsHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(txfResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(lbVolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(6, 6, 6))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jsHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarFilaMI)
                    .addComponent(btnEliminarFilaMI)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Madera Ingresada F5", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("MaderaIngresadaF5");

        jtProductosAserrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Calidad", "Ancho", "Espesor", "Largo", "UM (PT / Piezas, PT)", "Num de Piezas", "Total (PT)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProductosAserrados);
        if (jtProductosAserrados.getColumnModel().getColumnCount() > 0) {
            jtProductosAserrados.getColumnModel().getColumn(0).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(1).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(2).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(3).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(4).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(5).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(6).setResizable(false);
            jtProductosAserrados.getColumnModel().getColumn(7).setResizable(false);
        }

        btnAgregaFilaPA.setText("Agregar Fila");
        btnAgregaFilaPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaFilaPAActionPerformed(evt);
            }
        });

        btnEliminaFilaPA.setText("Eliminar Fila");
        btnEliminaFilaPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaFilaPAActionPerformed(evt);
            }
        });

        btnGuardarF6.setText("Guardar");
        btnGuardarF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarF6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Vol. Total: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregaFilaPA)
                .addGap(18, 18, 18)
                .addComponent(btnEliminaFilaPA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 852, Short.MAX_VALUE)
                .addComponent(btnGuardarF6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblPAVolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPAVolTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregaFilaPA)
                    .addComponent(btnEliminaFilaPA)
                    .addComponent(btnGuardarF6))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos Aserrados F6", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("ProductosAserradosF6");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Procesado en el dia (Turno)", "M3 Rollo" , null},
                {"Coeficiente de Aserrio", "Vol Aserrado (PT) / Vol  en Rollo(M3)", null},
                {"Rendimiento", "Vol en Tabla (PT) / Vol en Rollo (M3)", null},
                {"Volumen desperdicio", "Vol ingresado  a Aserrar / Vol  Aserrado", null},
                {"Acumulado Madera en Rollo", "M3 Rollo", null},
                {"Acumulado Madera Aserrada", "Vol en Tabla (PT) / M3 Rollo", null}
            },
            new String [] {
                "Concepto", "Unidades", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conceptos", jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName("Conceptos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Formato de Productos y Subproductos Aserrados");

        jLabel2.setText("Unidad de Aprovechamiento Forestal Comunal");

        jLabel3.setText("Reporte Diario de Ingreso y Produccion de Madera en la Unidad de Aprovechamiento forestal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizaTabla( TableModelEvent evento ){
        if(evento.getType() == TableModelEvent.UPDATE){
            
            tabla = ((DefaultTableModel)(evento.getSource()) );
            
            int fila = evento.getFirstRow();
            int columna = evento.getColumn();
            
            if( columna != 2 && columna != 4){
                return;
            }try{
                
                if( columna  == 2 ){
                    
                    System.out.println("Hola");
                    int largo = jcbLargos.getSelectedIndex();
                    
                    if (largo == 2){
                        
                        JFrame frame = new JFrame("Largos");
                        String nlargo = JOptionPane.showInputDialog(frame, "Ingrese el largo:");
                        largos = Double.parseDouble(nlargo);
                        
                        Object [] l = new Object[4];
                        l[0] = "1.25";
                        l[1] = "2.26";
                        l[2] = "Especiales";
                        l[3] = nlargo;
                        
                        jcbLargos = new JComboBox(l);
                        TableColumn  columnaL = jtRMR.getColumnModel().getColumn(2);
                        TableCellEditor tceL = new DefaultCellEditor(jcbLargos);
                        columnaL.setCellEditor(tceL);  
                        jcbLargos.setSelectedItem(nlargo);
                        
                    }else if(largo == 1){
                       largos = 2.26;
                    }else if(largo == 0){
                       largos = 1.25;
                    }
                    
                }else if( columna == 4 ){
                    d1 = ((Number) tabla.getValueAt(fila,3)).doubleValue();
                    d2 = ((Number) tabla.getValueAt(fila,4)).doubleValue();
                    double dos = Math.pow( d1*d2 / 2 , 2 );

                    
                    a = new BigDecimal(dos);
                    a = a.setScale(2, RoundingMode.HALF_UP);
                    
                    tabla.setValueAt( a.doubleValue() ,fila, 5);
                    
                    uno = Math.PI / 4;
                    
                    Voltroza = uno * a.doubleValue() * largos;
                    
                    
                    b = new BigDecimal(Voltroza);
                    b = b.setScale(2, RoundingMode.HALF_UP);
                    
                    tabla.setValueAt(b.doubleValue(), fila, 6);
                       
                    volTotal += Voltroza;
                    lbVolTotal.setText( decimales.format(volTotal) );
                }     
            }catch(NullPointerException e){
            }          
        }
    }
    
    private void actualizaTabla2 (TableModelEvent evento){
        if(evento.getType() == TableModelEvent.UPDATE){
            int fila = evento.getFirstRow();
            int columna = evento.getColumn();
            double a, b, c, d = 0, i;            
            
            if( columna != 2 && columna != 3 && columna != 4 && columna != 6){
                return;
            }try{
                
                if (columna == 6){
                    if(tabla2.getValueAt(fila, 5) != null){
                        i = Integer.parseInt(tabla2.getValueAt(fila, 6).toString());
                        d = Double.parseDouble(tabla2.getValueAt(fila, 5).toString());
                        tabla2.setValueAt(i*d, fila, 7);
                        
                        volTotal2 += i*d;
                        lblPAVolTotal.setText(decimales.format(volTotal2));
                    }
                }else{
                    if(tabla2.getValueAt(fila, 2) != null && tabla2.getValueAt(fila, 3) != null &&
                            tabla2.getValueAt(fila, 4) != null){
                        a = Double.parseDouble(tabla2.getValueAt(fila, 2).toString());
                        b = Double.parseDouble(tabla2.getValueAt(fila, 3).toString());
                        c = Double.parseDouble(tabla2.getValueAt(fila, 4).toString());
                        
                        d = (a*b*c) / 12;
                        tabla2.setValueAt(d, fila, 5);
                        
                    }     
                }
            }catch(NullPointerException e){
            }
        }
    }
            
    private void btnEliminaFilaPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaFilaPAActionPerformed
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) jtProductosAserrados.getModel();

        int f = jtProductosAserrados.getSelectedRow();

        if (f < 0 ){
            JOptionPane.showMessageDialog(null,
                "Debe seleccionar una fila de la tabla" );
        }else {
            int confirmar = JOptionPane.showConfirmDialog(null,
                "Esta seguro que desea Eliminar el registro? ");

            if(JOptionPane.OK_OPTION==confirmar) {
                Object valueAt = tabla2.getValueAt(jtProductosAserrados.getSelectedRow(), 7);
                volTotal2 = volTotal2 - Double.parseDouble(valueAt.toString());
                lblPAVolTotal.setText(decimales.format(volTotal2));
                modelo.removeRow(f);
            }
        }
    }//GEN-LAST:event_btnEliminaFilaPAActionPerformed

    private void btnAgregaFilaPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaFilaPAActionPerformed
        // TODO add your handling code here:
        tabs(false, true, false);
        if(tabla2.getRowCount() > 0){
            if(filallena(jtProductosAserrados)){
                tabla2.addRow(new Object[]{}); 
            }else
                JOptionPane.showMessageDialog(null, "Termine de llenar la fila");
        }else
            tabla2.addRow(new Object[]{});   
    }//GEN-LAST:event_btnAgregaFilaPAActionPerformed

    private void btnEliminarFilaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaMIActionPerformed
        // TODO add your handling code here:
                
        if (tabla.getRowCount() > 0 ){
            if (filallena(jtRMR)){ 
                int confirmar = JOptionPane.showConfirmDialog(null,
                "Esta seguro que desea Eliminar el registro? ");            
            if (JOptionPane.OK_OPTION == confirmar){
                Object valueAt = tabla.getValueAt(jtRMR.getSelectedRow(), 6);
                volTotal = volTotal - Double.parseDouble(valueAt.toString());
                lbVolTotal.setText( decimales.format(volTotal) );
                int selectedRow = jtRMR.getSelectedRow();
                tabla.removeRow(selectedRow);     
                for (int i= 0; i < tabla.getRowCount(); i++){
                    jtRMR.setValueAt(i + 1, i, 0);
                }
            }               
            }else
                JOptionPane.showMessageDialog(null, "Termine de llenar la fila");
           }else
            JOptionPane.showMessageDialog(null, "Agregre una fila primero!");
        //----------------------------------------------------------------------
    }//GEN-LAST:event_btnEliminarFilaMIActionPerformed

    private void btnAgregarFilaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaMIActionPerformed
        if (comprueba()){            
            this.bloqueo();
            if (tabla.getRowCount() > 0){               
                if(filallena(jtRMR)){ 
                    tabla.addRow(new Object[]{});      
                    int value = tabla.getRowCount();           
                    tabla.setValueAt(value, value -1, 0);  
                    fila = value; 
                }else
                    JOptionPane.showMessageDialog(null,
                            "Termine de llenar la fila" );
            }else{
                tabla.addRow(new Object[]{});  
                int value = tabla.getRowCount();
                tabla.setValueAt(value, value -1, 0);
            }          
        }else 
            JOptionPane.showMessageDialog(null,
                    "Termine de llenar los campos");
    }//GEN-LAST:event_btnAgregarFilaMIActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        comprueba();
        if(tabla.getRowCount() > 0 ){
            
            if (filallena(jtRMR)){
                System.out.println("Estamos guardando!!!"); 
                this.liberar();
                this.limpiar();
                tabs(true, true, true);
                
            }else
                JOptionPane.showMessageDialog(null, "Termine de  Llenar la Fila");
        }else
            JOptionPane.showMessageDialog(null, "Agrege una Fila");
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txfResponsableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfResponsableKeyTyped
        // TODO add your handling code here:
        tabs(true, false, false);        
    }//GEN-LAST:event_txfResponsableKeyTyped

    private void txfComunidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfComunidadKeyTyped
        // TODO add your handling code here:
        tabs(true, false, false);
    }//GEN-LAST:event_txfComunidadKeyTyped

    private void btnGuardarF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarF6ActionPerformed
        // TODO add your handling code here:
        if(tabla2.getRowCount() > 0 ){
            
            if (filallena(jtProductosAserrados)){
                System.out.println("Estamos guardando!!!"); 
                
                volTotal2 = 0.0;
                lblPAVolTotal.setText(decimales.format(volTotal2));
                
                tabs(true, true, true);
                tabla2.setRowCount(0);
                
                
            }else
                JOptionPane.showMessageDialog(null, "Termine de  Llenar la Fila");
        }else
            JOptionPane.showMessageDialog(null, "Agrege una Fila");
        
    }//GEN-LAST:event_btnGuardarF6ActionPerformed

    private boolean comprueba(){
        boolean com = false;      
        if ( !this.txfComunidad.getText().isEmpty() && !this.txfResponsable.getText().isEmpty() ){  
            com = true;
        }        
        return com;
    }
    
    private void bloqueo(){
        this.txfComunidad.setEditable(false);
        this.txfResponsable.setEditable(false);
        this.jcbGenero.setEnabled(false);
        this.jcbProcedencia.setEnabled(false);
        this.dcFechaIngreso.setEnabled(false);
        this.jsHoraEntrada.setEnabled(false);
    }
    
    private void tabs( boolean n1, boolean n2, boolean n3){
        jTabbedPane1.setEnabledAt(0, n1);
        jTabbedPane1.setEnabledAt(1, n2);
        jTabbedPane1.setEnabledAt(2, n3);
    }
    
    public void setPiezas(int p){
        this.diame1 = p;
    }
    
     private boolean filallena(JTable tb){
        boolean va = true;       
        int r = tb.getRowCount();        
        for (int i = 1; i < tb.getColumnCount(); i++){           
            if ( tb.getValueAt(r -1, i) == null) {
                va = false;
                break;
            }else
                System.out.println(tb.getValueAt(r -1, i));      
        }       
        return va;
    }
     
     private void liberar(){
        this.txfComunidad.setEditable(true);
        this.txfResponsable.setEditable(true);
        this.jcbGenero.setEnabled(true);
        this.jcbProcedencia.setEnabled(true);
        this.dcFechaIngreso.setEnabled(true);
        this.jsHoraEntrada.setEnabled(true);
     }
     
     private void limpiar(){
        this.txfComunidad.setText("");
        this.txfResponsable.setText("");
        volTotal = 0.0;
        lbVolTotal.setText( decimales.format(volTotal) );
                
        tabla.setRowCount(0);
        jtRMR.setModel(new DefaultTableModel());
        tabla = (DefaultTableModel) jtRMR.getModel();
        
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formato6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formato6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formato6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formato6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formato6().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregaFilaPA;
    private javax.swing.JButton btnAgregarFilaMI;
    private javax.swing.JButton btnEliminaFilaPA;
    private javax.swing.JButton btnEliminarFilaMI;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarF6;
    private datechooser.beans.DateChooserCombo dcFechaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox jcbGenero;
    private javax.swing.JComboBox jcbProcedencia;
    private javax.swing.JSpinner jsHoraEntrada;
    private javax.swing.JTable jtProductosAserrados;
    private javax.swing.JTable jtRMR;
    private javax.swing.JLabel lbVolTotal;
    private javax.swing.JLabel lblPAVolTotal;
    private javax.swing.JTextField txfComunidad;
    private javax.swing.JTextField txfResponsable;
    // End of variables declaration//GEN-END:variables
}
