/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import com.sun.glass.events.KeyEvent;
import java.awt.Component;
import java.awt.Point;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.gt;
import static javax.management.Query.lt;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author fservin
 */
public class Formato4 extends javax.swing.JFrame {
    private DefaultTableModel tabla;
    private String [] Largos =  {"1.25","2.62","Especiales"};
    private int fila, D1, D2;
    private double L, volTotal,Voltroza,largos;  
    DecimalFormat decimales = new DecimalFormat("0.00");
    private JComboBox jcbClasificacion;
    private JComboBox jcbLargos;
   
    private void anadeListenerAlModelo(JTable tabla) {
        tabla.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent evento) {
                actualizaSumas(evento);
            }  
        });
    }
    /**
     * Creates new form Formato4
     */
    @SuppressWarnings("empty-statement")
    public Formato4() {
        initComponents();
        
        anadeListenerAlModelo(jtRMR);
        tabla = (DefaultTableModel) jtRMR.getModel();
        
        jsHoraRemision  = new JSpinner( new SpinnerDateModel() );
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jsHoraRemision, "HH:mm:ss");
        jsHoraRemision.setEditor(timeEditor);
        jsHoraRemision.setValue( new Date() );
        
        String [] lClasificados = {"Primario","Secundario","Tercera","Celulosico","Medidas Especiales","Puntales","Morillos"};
        jcbClasificacion = new JComboBox(lClasificados);
        TableColumn columnaC = jtRMR.getColumnModel().getColumn(1);
        TableCellEditor tceC = new DefaultCellEditor(jcbClasificacion);
        columnaC.setCellEditor(tceC);
        
        String [] lLargos = {"1.25","2.26","Especiales"};  
        jcbLargos = new JComboBox(lLargos);
        TableColumn  columnaL = jtRMR.getColumnModel().getColumn(2);
        TableCellEditor tceL = new DefaultCellEditor(jcbLargos);
        columnaL.setCellEditor(tceL);      
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        String [] clasificados = {"Primario","Secundario","Otros"};
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtRMR = new javax.swing.JTable();
        txfDataTransporte = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tbFSC = new javax.swing.JToggleButton();
        txfNRemision = new javax.swing.JTextField();
        tbRemisionado = new javax.swing.JToggleButton();
        btnAgregarFila = new javax.swing.JButton();
        btnEliminarFila = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txfDataChofer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbVolTotal = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel( date, null, null, Calendar.HOUR_OF_DAY );
        jsHoraRemision = new javax.swing.JSpinner(sm);
        Date date2 = new Date();
        SpinnerDateModel sm2 =
        new SpinnerDateModel( date2, null, null, Calendar.HOUR_OF_DAY );
        jsHoraRecepcion = new javax.swing.JSpinner(sm2);
        jLabel9 = new javax.swing.JLabel();
        txfNombreDocumentador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txfNombreVigilante = new javax.swing.JTextField();
        cbProcedencia = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txfNumEnbarque = new javax.swing.JTextField();
        dcDateRemision = new datechooser.beans.DateChooserCombo();
        dcDaterecepcion = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recepcion de Madera en Rollo");
        jLabel1.setToolTipText("");

        jLabel2.setText("Recibo de troceria ingresada a patio de aserradero");

        jLabel3.setText("Procedencia :");

        jLabel4.setText("FSC :");

        jLabel5.setText("Remisionado :");

        jLabel6.setText("Numero de Remision :");

        jLabel7.setText("Datos de Transporte :");

        jLabel8.setText("Fecha Recepcion :");

        jtRMR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Pieza", "Clasificacion", "Largo", "D1", "D2", "DM", "Vol M3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRMR.setColumnSelectionAllowed(true);
        jtRMR.getTableHeader().setReorderingAllowed(false);
        jtRMR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRMRFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jtRMR);
        jtRMR.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtRMR.getColumnModel().getColumnCount() > 0) {
            jtRMR.getColumnModel().getColumn(0).setResizable(false);
            jtRMR.getColumnModel().getColumn(1).setResizable(false);
            jtRMR.getColumnModel().getColumn(2).setResizable(false);
            jtRMR.getColumnModel().getColumn(3).setResizable(false);
            jtRMR.getColumnModel().getColumn(4).setResizable(false);
            jtRMR.getColumnModel().getColumn(5).setResizable(false);
            jtRMR.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbFSC.setText("Si");
        tbFSC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbFSCMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FSCMouse(evt);
            }
        });

        txfNRemision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txfNRemisionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNRemisionKeyTyped(evt);
            }
        });

        tbRemisionado.setText("Si");
        tbRemisionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbRemisionadoMousePressed(evt);
            }
        });
        tbRemisionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRemisionadoActionPerformed(evt);
            }
        });

        btnAgregarFila.setText("Agregar Fila");
        btnAgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFilaActionPerformed(evt);
            }
        });

        btnEliminarFila.setText("Eliminar Fila");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel10.setText("Datos del Chofer :");

        jLabel11.setText("Fecha Remision :");

        jLabel12.setText("Hora Remision :");

        jLabel13.setText("Hora Recepcion :");

        jLabel14.setText("Formato 04");

        jLabel15.setText("Volumen Total: ");

        JSpinner.DateEditor de = new JSpinner.DateEditor(jsHoraRemision, "HH:mm:ss");
        jsHoraRemision.setEditor(de);

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(jsHoraRecepcion, "HH:mm:ss");
        jsHoraRecepcion.setEditor(de2);

        jLabel9.setText("Nombre del Documentador:");

        jLabel16.setText("Nombre del Vigilante o Responsable de Recepcion");

        cbProcedencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Volumen Comunidad", "Compra Externa", "Maquila" }));

        jLabel17.setText("Numero de Lista de  Embarque :");

        txfNumEnbarque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfNumEnbarqueKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel2))
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfNombreDocumentador, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tbFSC)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txfDataChofer, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txfDataTransporte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tbRemisionado)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txfNRemision, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(txfNumEnbarque, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dcDateRemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jsHoraRemision, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(jsHoraRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbVolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dcDaterecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregarFila)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarFila)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(770, 770, 770)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txfNombreVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfNombreDocumentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfNombreVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(42, 42, 42)
                                .addComponent(tbFSC)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbRemisionado)
                                    .addComponent(jLabel6)
                                    .addComponent(txfNRemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(txfNumEnbarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfDataChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfDataTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(dcDateRemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dcDaterecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jsHoraRemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jsHoraRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(lbVolTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnAgregarFila)
                    .addComponent(btnEliminarFila))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void update(){
                
    }
    
    private void actualizaSumas(TableModelEvent evento) {
        
        if(evento.getType() == TableModelEvent.UPDATE){
            
            TableModel modelo = ((DefaultTableModel) (evento.getSource()));
            int fila = evento.getFirstRow();
            int columna = evento.getColumn();
            double d1 = 0,d2 = 0,uno = 0;
            BigDecimal a = null,b;
  
            if (columna != 2 && columna != 4 ){
                return ; 
            }try{
               
                if ( columna == 2 ){
                    int largo = jcbLargos.getSelectedIndex();
                    
                    if (largo == 2){
                        
                        JFrame frame = new JFrame("Largos");
                        String nlargo = JOptionPane.showInputDialog(frame, "Ingrese el largo:");
                        largos = Double.parseDouble(nlargo);
                        
                        Object [] l = new Object[4];
                        l[0] = "1.25";
                        l[1] = "2.26";
                        l[2] = "Especiales";
                        l[3] = nlargo;
                        
                        jcbLargos = new JComboBox(l);
                        TableColumn  columnaL = jtRMR.getColumnModel().getColumn(2);
                        TableCellEditor tceL = new DefaultCellEditor(jcbLargos);
                        columnaL.setCellEditor(tceL);  
                        jcbLargos.setSelectedItem(nlargo);
                        
                    }else if(largo == 1){
                       largos = 2.26;
                    }else if(largo == 0){
                       largos = 1.25;
                    }
                    
                    if( uno > 0 &&  a.doubleValue()  > 0){
                        Voltroza = uno * a.doubleValue() * largos;
                        
                        b = new BigDecimal(Voltroza);
                        b = b.setScale(2, RoundingMode.HALF_UP);

                        modelo.setValueAt(b.doubleValue(), fila, 6);
                        
                        volTotal += Voltroza;
                        lbVolTotal.setText( decimales.format(volTotal) );
                    }
                   
                }else if(columna == 4){
                    
                    d1 = ((Number) modelo.getValueAt(fila,3)).doubleValue();
                    d2 = ((Number) modelo.getValueAt(fila,4)).doubleValue();
                    double dos = Math.pow( d1*d2 / 2 , 2 );

                    a = new BigDecimal(dos);
                    a = a.setScale(2, RoundingMode.HALF_UP);
                    
                    modelo.setValueAt( a.doubleValue() ,fila, 5);
                                       
                    uno = Math.PI / 4;
                    
                    Voltroza = uno * a.doubleValue() * largos;
                                        
                    b = new BigDecimal(Voltroza);
                    b = b.setScale(2, RoundingMode.HALF_UP);
                    
                    modelo.setValueAt(b.doubleValue(), fila, 6);
                                         
                    volTotal += Voltroza;
                    lbVolTotal.setText( decimales.format(volTotal) );
                }     
            }catch (NullPointerException e) {
                // La celda que ha cambiado esta vacia.
            }     
        }
    }
    private void FSCMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FSCMouse
                     
    }//GEN-LAST:event_FSCMouse

    private void tbFSCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFSCMousePressed
        // TODO add your handling code here:
        if ("Si".equals(tbFSC.getText()))
        this.tbFSC.setText("No");
        else
            this.tbFSC.setText("Si");
    }//GEN-LAST:event_tbFSCMousePressed

    private void tbRemisionadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRemisionadoMousePressed
        // TODO add your handling code here:
        if ("Si".equals(tbRemisionado.getText())){
            this.tbRemisionado.setText("No");
            this.txfNRemision.setText("SN");
            this.txfNRemision.setEditable(false);
        }else{
            this.tbRemisionado.setText("Si");
            this.txfNRemision.setEditable(true);
            this.txfNRemision.setText("");  
        }
    }//GEN-LAST:event_tbRemisionadoMousePressed

    private void btnAgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFilaActionPerformed
        // TODO add your handling code here:
        
        if (comprueba() ){
                        
            this.bloqueo();
            
            if ( tabla.getRowCount() > 0  ){
                System.out.println(tabla.getRowCount());                
                if (filallena(jtRMR)){
                    tabla.addRow(new Object[]{});      
                    int value = tabla.getRowCount();           
                    tabla.setValueAt(value, value -1, 0);  
                    fila = value; 
                }else
                    JOptionPane.showMessageDialog(null,
                        "Termine de llenar la fila" );
            }else{
                tabla.addRow(new Object[]{});      
                int value = tabla.getRowCount();           
                tabla.setValueAt(value, value -1, 0);  
                fila = value;                   
            }            
        }else {
            JOptionPane.showMessageDialog(null,
                "Termine de llenar los campos" );
        }     
    }//GEN-LAST:event_btnAgregarFilaActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        // TODO add your handling code here:
        if (tabla.getRowCount() > 0 ){
            if (filallena(jtRMR)){ 
                int confirmar = JOptionPane.showConfirmDialog(null,
                "Esta seguro que desea Eliminar el registro? ");            
            if (JOptionPane.OK_OPTION == confirmar){
                Object valueAt = tabla.getValueAt(jtRMR.getSelectedRow(), 6);
                volTotal = volTotal - Double.parseDouble(valueAt.toString());
                lbVolTotal.setText( decimales.format(volTotal) );
                int selectedRow = jtRMR.getSelectedRow();
                tabla.removeRow(selectedRow);     
                for (int i= 0; i < tabla.getRowCount(); i++){
                    jtRMR.setValueAt(i + 1, i, 0);
                }
            }               
            }else
                JOptionPane.showMessageDialog(null, "Termine de llenar la fila");
           }else
            JOptionPane.showMessageDialog(null, "Agregre una fila primero!");
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void bloqueo(){
        this.txfNombreDocumentador.setEditable(false);
        this.txfDataChofer.setEditable(false);
        this.txfDataTransporte.setEditable(false);
        this.txfNRemision.setEditable(false);
        this.txfNombreVigilante.setEditable(false);
        this.txfNumEnbarque.setEditable(false);
        
        this.cbProcedencia.setEnabled(false);
        this.tbFSC.setEnabled(false);
        this.tbRemisionado.setEnabled(false);
        this.dcDateRemision.setEnabled(false);
        this.dcDaterecepcion.setEnabled(false);
    }
    
    private boolean comprueba(){
        boolean com = false;
        
        if ( !this.txfNombreDocumentador.getText().isEmpty() && !this.txfNombreDocumentador.getText().isEmpty() && 
                !this.txfDataChofer.getText().isEmpty() && !this.txfDataTransporte.getText().isEmpty() && 
                !this.txfNRemision.getText().isEmpty() && !this.txfNombreVigilante.getText().isEmpty() && 
                !this.txfNumEnbarque.getText().isEmpty()){
            
            com = true;
        } 
        
        return com;
    }
    
    private boolean filallena(JTable tb){
        boolean va = true; 
        int r = tb.getRowCount();
        for (int i = 1; i < tb.getColumnCount(); i++){
            
            if ( tb.getValueAt(r -1, i) == null) {
                va = false;
                break;
            }else
                System.out.println(tb.getValueAt(r -1, i));      
        }
        return va;
    }
    
    private void tbRemisionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRemisionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRemisionadoActionPerformed

    private void jtRMRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRMRFocusLost
       
    }//GEN-LAST:event_jtRMRFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        this.txfNombreDocumentador.getText();
        this.txfNombreVigilante.getText();
        this.cbProcedencia.getSelectedItem();
        this.tbFSC.getText();
        this.tbRemisionado.getText();
        this.txfNRemision.getText();
        this.txfNumEnbarque.getText();
        this.txfDataChofer.getText();
        this.txfDataTransporte.getText();
        this.dcDateRemision.getSelectedDate();
        this.dcDaterecepcion.getSelectedDate();
        this.jsHoraRemision.getValue();
        this.jsHoraRecepcion.getValue();
        
        if (comprueba()){
            limpia();
            
        }else
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos");
     
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txfNRemisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNRemisionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNRemisionKeyReleased

    private void txfNRemisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNRemisionKeyTyped
        // TODO add your handling code here:
        digitos(evt);
    }//GEN-LAST:event_txfNRemisionKeyTyped

    private void txfNumEnbarqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfNumEnbarqueKeyTyped
        // TODO add your handling code here:
        digitos(evt);
    }//GEN-LAST:event_txfNumEnbarqueKeyTyped

    private void digitos(java.awt.event.KeyEvent evt){
        char letra = evt.getKeyChar();
        
        if(((letra < '0') || 
                (letra > '9')) &&
                (letra != '\b')){
            evt.consume();
        }
    }
    
    private void limpia(){
        
        this.txfNombreDocumentador.setEditable(true);
        this.txfDataChofer.setEditable(true);
        this.txfDataTransporte.setEditable(true);
        this.txfNRemision.setEditable(true);
        this.txfNombreVigilante.setEditable(true);
        this.txfNumEnbarque.setEditable(true);
        
        this.cbProcedencia.setEnabled(true);
        this.tbFSC.setEnabled(true);
        this.tbRemisionado.setEnabled(true);
        this.dcDateRemision.setEnabled(true);
        this.dcDaterecepcion.setEnabled(true);
        
        this.txfNombreDocumentador.setText("");
        this.txfDataChofer.setText("");
        this.txfDataTransporte.setText("");
        this.txfNRemision.setText("");
        this.txfNombreVigilante.setText("");
        this.txfNumEnbarque.setText("");
                
        volTotal = 0.0;
        lbVolTotal.setText( decimales.format(volTotal) );
                
        tabla.setRowCount(0);
        jtRMR.setModel(new DefaultTableModel());
        tabla = (DefaultTableModel) jtRMR.getModel();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formato4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formato4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formato4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formato4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formato4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFila;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbProcedencia;
    private datechooser.beans.DateChooserCombo dcDateRemision;
    private datechooser.beans.DateChooserCombo dcDaterecepcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jsHoraRecepcion;
    private javax.swing.JSpinner jsHoraRemision;
    private javax.swing.JTable jtRMR;
    private javax.swing.JLabel lbVolTotal;
    private javax.swing.JToggleButton tbFSC;
    private javax.swing.JToggleButton tbRemisionado;
    private javax.swing.JTextField txfDataChofer;
    private javax.swing.JTextField txfDataTransporte;
    private javax.swing.JTextField txfNRemision;
    private javax.swing.JTextField txfNombreDocumentador;
    private javax.swing.JTextField txfNombreVigilante;
    private javax.swing.JTextField txfNumEnbarque;
    // End of variables declaration//GEN-END:variables
}
